### PR TITLE
fix: Sponsor footer layout

### PR DESCRIPTION
**Pull request by sourcefilter**
fixes Flexbox params and replaces <ResponsiveImage> with  tag to solve an issue with too-large sizer div

### CODE REVIEW

**Comment by sourcefilter** [comment]
Meant to include these links originally:
https://deploy-preview-158--ucla-library-storybook.netlify.app/?path=/story/block-sponsor--default
https://deploy-preview-158--ucla-library-storybook.netlify.app/?path=/story/footer-sponsor--default

**Review by jendiamond — COMMENTED** [review]
🍰

**Review by jendiamond — APPROVED** [review]
🥮

**Pull request merged**
