### PR TITLE
feat: Apps-2706 create BlockEventDetail component

### PR DESCRIPTION
**Pull request by farosFreed**
Connected to [APPS-2706](https://jira.library.ucla.edu/browse/APPS-2706)

**Component Created:** BlockEventDetail.vue

**Stories:** ~/stories/BlockEventDetail.stories.js

**Spec:** ~/stories/BlockEventDetail.spec.js

**Notes:**

BlockEventDetail component was created based on this spec: https://github.com/UCLALibrary/ucla-library-website-components/issues/519

I did start with the icon-with-link component as instructed, but a few things made me decide not to use it:

- it doesn't have the icons I'd need, Id need to add them to the component (easy to do though)
- I couldn't figure out a good way to get the location item to work with it, because it can have multiple locations with different links next to the same icon, and IconWithLink doesn't really support that case. 

If others have ideas about better ways to solve these issues than what I have, let me know. 

This component MAY need to implement a 'CalendarButton' or 'ButtonWithDropDownMenu' component or whatever we will call it, but I added a slot for that so it should be optional for us to implement that from the page level instead. 

**Checklist:**

-   [X] I checked that it is working locally in the dev server
-   [X] I checked that it is working locally in the storybook
-   [X] I checked that it is working locally in the 
library-website-nuxt dev server
-   [X] I added a screenshot of it working
-   [ ] UX has reviewed and approved this
-   ~~[] I assigned this PR to someone on the dev team to review~~
-   [X] I used a conventional commit message
-   [X] I assigned myself to this PR

[APPS-2706]: https://uclalibrary.atlassian.net/browse/APPS-2706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by farosFreed** [comment]
Screenshot 2024-06-24 at 2 03 26 PM

**Review by jendiamond — APPROVED** [review]
Thanks for updating the stories.
Looks good.
🍰

**Pull request merged**
