### PR TITLE
feat: APPS-2777 fix nitro crawling issue

### PR DESCRIPTION
**Pull request by pghorpade**
Connected to [APPS-2777](https://jira.library.ucla.edu/browse/APPS-777)

This PR fixes an issue of Nuxt nitro not able to crawl our component router links or anchor tags. 

[APPS-2777]: https://uclalibrary.atlassian.net/browse/APPS-2777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by farosFreed — APPROVED** [review]
Looks good, cool fix, is there anything we should document here about that resolve dirname bit? Was it causing the problem? 

Approved ✅

**Comment by pghorpade** [comment]
> Looks good, cool fix, is there anything we should document here about that resolve dirname bit? Was it causing the problem?
> 
> Approved ✅

@farosFreed It was not required , as vite internally knows where the entry file is.

**Pull request merged**
