### PR TITLE
feat: Apps-2704 finish tags component part 2

### PR DESCRIPTION
**Pull request by farosFreed**
Connected to [APPS-2704](https://jira.library.ucla.edu/browse/APPS-2704)

**Components Updated:**BlockTag.vue, BlockRemoveSearchFilter.vue + theme files and stories

**Notes:**

Icons are in, everything should be true to mockups

**Checklist:**

-   [X] I checked that it is working locally in the dev server
-   [X] I checked that it is working locally in the storybook
-   [ ] I checked that it is working locally in the 
library-website-nuxt dev server
-   [ ] I added a screenshot of it working
-   [ ] UX has reviewed and approved this
-   [ ] I assigned this PR to someone on the dev team to review
-   [X] I used a conventional commit message
-   [X] I assigned myself to this PR

[APPS-2704]: https://uclalibrary.atlassian.net/browse/APPS-2704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by tinuola — APPROVED** [review]
@farosFreed Looks good. 👍🏽 
Curious: What's the purpose of using router/routes in BlockRemoveSearchFilter.stories file?

**Comment by farosFreed** [comment]
@tinuola github wouldn't let me reply directly:

all the route stuff is there for because on the library site, this component looks at the route to determine the border color of the block (/visit/x has a different color than /help/x, etc). 

For FTVA, the route is irrelevant to the styles, but the component still expects a route so the story must have it - it doesnt matter what route I pass.

**Review by tinuola — APPROVED** [review]

**Pull request merged**
