### PR TITLE
feat: APPS-2467 BannerHeader component

### PR DESCRIPTION
**Pull request by tinuola**
Connected to [APPS-2467](https://jira.library.ucla.edu/browse/APPS-2467)

**Component Created:** BannerHeader.vue

**Stories:** ~/stories/BannerHeader.stories.js

**Spec:** ~/stories/BannerHeader.spec.js

**Notes:**

- Component uses two components that have not yet been migrated: ResponsiveVideo and BlockForm; they will be added in subsequent tickets:
  - https://uclalibrary.atlassian.net/browse/APPS-2507
  - https://uclalibrary.atlassian.net/browse/APPS-2518 

**Checklist:**

-   [x] I checked that it is working locally in the dev server
-   [x] I checked that it is working locally in the storybook
-   [x] I checked that it is working locally in the 
library-website-nuxt dev server
-   [ ] I added a screenshot of it working
-   [x] UX has reviewed and approved this
-   [x] I assigned this PR to someone on the dev team to review
-   [x] I used a conventional commit message
-   [x] I assigned myself to this PR

[APPS-2467]: https://uclalibrary.atlassian.net/browse/APPS-2467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by axamei — DISMISSED** [review]
👍

**Comment by tinuola** [comment]
@axamei I pushed some minor fixes before I saw you had already approved the PR. Can you do another quick scan? Apologies for the double work.

**Review by axamei — APPROVED** [review]
👍

**Pull request merged**
