### PR TITLE
feat: APPS-2999 Add BlockCTA FTVA variants

### PR DESCRIPTION
**Pull request by tinuola**
Connected to [APPS-2999](https://jira.library.ucla.edu/browse/APPS-2999)

**Component Updated:** BlockCallToAction.vue

**Stories:** 
- ~/stories/BlockCallToAction.stories.js
- ~/stories/TwoColLayoutWStickySideBar.stories.js

**Notes:**
- Updated design tokens from `5.23.0` to ~~`5.26.0`~~ `5.27.0`
- Refactored component to use CAPI, Typescript and new theming setup
- Created FTVA `Slim` variant of CTA block
  - Included additional icons, new `isCentered` prop to cue default or left (slim) alignment
  - Variant's width should be set/constrained by a containing/parent element
- Updated component stories with new variant

<br>

**StoryBook Previews:**
- FTVA Slim, Left-Aligned, Titled, Using global data 
  - https://deploy-preview-630--ucla-library-storybook.netlify.app/?path=/story/block-call-to-action--ftva-slim-cta-titled

- FTVA Slim, Left-Aligned, No Title
  - https://deploy-preview-630--ucla-library-storybook.netlify.app/?path=/story/block-call-to-action--ftva-slim-cta-no-title

- FTVA Slim, Left-Aligned, Long Text
  - https://deploy-preview-630--ucla-library-storybook.netlify.app/?path=/story/block-call-to-action--ftva-slim-cta-long-text

- FTVA Slim in 2-Column Sidebar Layout
  - https://deploy-preview-630--ucla-library-storybook.netlify.app/?path=/story/layout-2-column-layout-with-sticky-sidebar--ftva-slim-cta 

- FTVA CTA Default (Mimics component's current use on Library, MEAP sites)
  - https://deploy-preview-630--ucla-library-storybook.netlify.app/?path=/story/block-call-to-action--ftva-cta-default

<br>

**Local Preview:**
- Download icon can be added as a pseudo-element for full-width component at the page level:
cta-with-download-icon

<br>

**Checklist:**

-   [x] I checked that it is working locally in the dev server
-   [x] I checked that it is working locally in the storybook
-   ~~[ ] I checked that it is working locally in the 
library-website-nuxt dev server~~
-   [x] I added a screenshot of it working
-   [ ] UX has reviewed and approved this
-   [x] I have requested a PR review from the Dev team
-   [x] I used a conventional commit message
-   [x] I assigned myself to this PR

[APPS-2999]: https://uclalibrary.atlassian.net/browse/APPS-2999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by farosFreed — CHANGES_REQUESTED** [review]
Overall it looks really great, all the various call to action stories seem to be preserved the new the ones look good. 

I have a few concerns:
- there seems to be some unrelated buttondropdown.vue changes. Should these be removed?

- the globalType prop is difficult to understand. Is there a case where we need a style sometimes in the FTVA and not others, and so we added an additional prop? If that's the case, can we name the prop closer to what it does? Does it force a certain style? I found it difficult to understand, and the enum with the same name added additional, cognitive load when trying to understand it. 

- lastly, I see there are notes about certain page level styles. I wonder if we should instead do sidebar level styles to add some things? For instance, should the CTA always have rounded corners in the sidebar? (It does in the mockups Ive seen). Basically, if its a style we'd need to add every time we use it in the 2ColLayout component, let's add it there rather than the page. What do you think?

**Comment by axamei** [comment]
@tinuola Let's adjust the heading:
```
.title {
  line-height: 1.2;
  margin-bottom: 4px;
} 
```

**Review by farosFreed — APPROVED** [review]
Looks good!

**Pull request merged**
